# Generated by Django 2.0.2 on 2018-03-09 13:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_auto_20180304_1200'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='summary',
            field=models.TextField(default='Some book', help_text='Enter a brief description of the book', max_length=1000),
        ),
    ]
